# Generated by Django 3.2.12 on 2022-02-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20220203_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
