# Generated by Django 3.2.12 on 2022-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default='Question No. ', max_length=255, verbose_name='Title'),
        ),
    ]
