# Generated by Django 3.2.12 on 2022-02-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20220203_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='category',
        ),
    ]
